
services:
  postgresql:
    image: docker.io/bitnami/postgresql:latest
    
    ports:
      - '5432:5432'

    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=SLDB

    volumes:
      - polls_pg_data:/bitnami/postgresql

volumes:
  polls_pg_data: